feat: add sns publish message
noverde/serpens pull request #12
Opened 2021-01-15 18:00 UTC by jaelzr

### Contain
- [x] New feature

### Details
* Add sns integration to publish messages

2021-01-15 18:39 UTC, JoaoVitorStein requested changes

2021-01-15 18:39 UTC, JoaoVitorStein commented on serpens/sns.py
> +    arn = f"arn:aws:sns:{AWS_REGION}:{AWS_ACCOUNT_ID}:{NOVERDE_EVENTS}"
recebe esse ARN como parâmetro, não é responsabilidade do serpens montar isso

2021-01-15 20:37 UTC, julianolf reviewed
Eu estou em dúvida apenas se deveríamos montar essa estrutura de mensagem dentro da função de envio ou se deveríamos separar, de forma que possamos utilizar essa mesma função para enviar mensagens em tópicos diferentes com outras estruturas de mensagem.

2021-01-15 20:51 UTC, ecanuto commented
> Eu estou em dúvida apenas se deveríamos montar essa estrutura de mensagem dentro da função de envio ou se deveríamos separar, de forma que possamos utilizar essa mesma função para enviar mensagens em tópicos diferentes com outras estruturas de mensagem.

Para mim, deveria ser o mesmo caso do SQS. Ficou bem legal.

2021-01-17 00:53 UTC, ecanuto approved these changes

2021-01-18 11:30 UTC, JoaoVitorStein approved these changes

2021-01-18 12:51 UTC, merged