feat: add sns create message event
noverde/serpens pull request #13
Opened 2021-01-18 16:02 UTC by jaelzr

### Contain
- [x] New feature

### Details
* Add sns create message event

2021-01-18 16:26 UTC, JoaoVitorStein requested changes

2021-01-18 16:26 UTC, JoaoVitorStein commented on serpens/sns.py
> +def message_event(category, event_type, aggregate_id, payload):
```suggestion
def build_event_message(category, event_type, aggregate_id, payload):
```

2021-01-18 16:26 UTC, JoaoVitorStein commented on serpens/sns.py
> +def message_event(category, event_type, aggregate_id, payload):
Acredito que o nome seja mais claro dessa maneira.

2021-01-19 18:49 UTC, julianolf commented on serpens/sns.py
> +def build_event_message(category, event_type, aggregate_id, payload):
O que acha de nomear de acordo com o tópico? Pensado que cada um teria uma estrutura e um conjunto de atributos diferentes.

E acho que se você está definindo uma estrutura de dados poderia usar uma classe para descrever essa estrutura em Python.

```python
@dataclass
class NoverdeEvents:
    category: str
    type: str
    aggregate_id: str
    payload: dict
    id: field(default_factory=uuid4)
    at: field(default_factory=datetime.utcnow)
    version: str = '1.0'

    @property
    def message(self):
        msg = {'default': json.dumps(asdict(self), cls=SchemaEncoder)}
        return msg

    @property
    def attributes(self):
        attrs = {"event_type": {"DataType": "String", "StringValue": self.type}}
        return attrs
```

E utilizaria mais ou menos assim:

```python
event = NoverdeEvents('category', 'type', '123', {'foo': 'bar'})
publish_message('topic', event.message, event.attributes)
```

2021-01-19 18:51 UTC, jaelzr commented on serpens/sns.py
> +def build_event_message(category, event_type, aggregate_id, payload):
achei legal, não tinha pensado dessa forma

2021-01-19 22:19 UTC, julianolf approved these changes
Ei sei que fui eu quem fez a sugestão mas agora fiquei em dúvida se `NoverdeEvents` não seria um problema por estar referenciando diretamente a Noverde. Talvez `DefaultMessage`? 🤔 

Acho melhor pedir a opinião do @ecanuto e do @JoaoVitorStein, quem sabe eles tem uma idéia melhor de nome.

Mas a estrutura em si eu gostei.

2021-01-20 12:55 UTC, merged